# Generated by Django 4.2.6 on 2024-09-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')], 'verbose_name': 'Yanglik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Taglar'},
        ),
    ]
